### ISSUE TITLE
[Feature Request] Support for HTTP POST with body

### ISSUE THREAD

**Issue by Patrick762** [bartbutenaers/node-red-contrib-sse-client#6]
Hello,
first of all, thanks for this node. This could solve many problems to integrate different services into Node Red and Home Assistant.

I tried using this node to read the event stream of "The Things network". This event stream uses POST requests (with json body) instead of GET. Could you please add POST requests to this node? If possiblem, the body should be read from "msg.body" or something like that.

**Comment by bartbutenaers** [comment]
Hi @Patrick762,

Very recently there was a similar request (see [here](https://discourse.nodered.org/t/announce-node-red-contrib-sse-client/1025/34?u=bartbutenaers)).  Unfortunately he got no feedback yet.

Bart

**Comment by bartbutenaers** [comment]
BTW you might have seen that this repo contains a (slightly) modified clone of the eventsource library.  But I am not going to add some PUT related modification to it, because then my clone gets too much out of sync with their original code.  Which would prevent me from updating to their newev versions in the future...

**Comment by Patrick762** [comment]
It seems like they will not add POST because it is not in the official EventSource specification.

https://github.com/EventSource/eventsource/pull/292
https://github.com/EventSource/eventsource/pull/112
https://github.com/EventSource/eventsource/pull/138

**Comment by Patrick762** [comment]
I added the POST method in my branch https://github.com/Patrick762/node-red-contrib-sse-client/tree/dev, but it seems like the server doesn't use any "normal" events (I do receive data in the buffer, but it is not sent as an event).

It seems like @hansju-11 also tried to use the "The things network" server (same url).

I'll close this issue because I don't think it's worth the time to solve this

**Comment by bartbutenaers** [comment]
@Patrick762,
Thanks for sharing your analysis!!
Bart

**Comment by hansju-11** [comment]
should we have a look at https://github.com/mpetazzoni/sse.js ? What do you thing?

**Comment by bartbutenaers** [comment]
Hi @hansju-11,
Sorry for the delay!  I am rather short of spare time...

From the comments of @Patrick762, I had understood that you use the same url, but it are no events?  So that sse.js wouldn't solve your problem?  Or didn't I understood this correctly?
